[pytest]
pythonpath = ..
addopts = -s -v --alluredir=reports/allure-results --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke cases
    topic: topic module
    index: index dictionary module
    skip_case: skipped cases
